# See: <./doc/SECRETS.md>

keys:
  - &omnara1 age1meufdn27h733757vg8swsfty5r2srghuxwerhkvm2swyr3ftrunqe7tqff
  - &phliptop-mbp age1mvqd856lguk3n2qzs73q6xcj7etgx6le5zy0ceyd96s9xpd36pasfakgcy
  - &phliptop-nitro age1t29pqpyt5wryjrryrhc8pc98ft6k3yn7r6yzx44yrkjmnw6kc9uqn43xpw

creation_rules:
  - path_regex: nixos/omnara1/secrets.yaml$
    key_groups:
      - age:
        - *omnara1
        - *phliptop-mbp
        - *phliptop-nitro
