[colors]
indexed_colors = [
  { color = "#b6927b", index = 16 },
  { color = "#b98d7b", index = 17 },
]

[colors.bright]
black = "#a6a69c"
blue = "#7fb4ca"
cyan = "#7aa89f"
green = "#87a987"
magenta = "#938aa9"
red = "#e46876"
white = "#c5c9c5"
yellow = "#e6c384"

[colors.normal]
black = "#0d0c0c"
blue = "#8ba4b0"
cyan = "#8ea4a2"
green = "#8a9a7b"
magenta = "#a292a3"
red = "#c4746e"
white = "#c8c093"
yellow = "#c4b28a"

[colors.primary]
background = "#12120f"
foreground = "#deddd3"

[colors.selection]
background = "#2d4f67"
foreground = "#c8c093"

[cursor.style]
blinking = "Off"
shape = "Block"

[font.bold]
style = "Semibold"

[font.bold_italic]
style = "Semibold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Regular"

[font.normal]
family = "Source Code Pro for Powerline"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"
