# GENERATED by ./pkgs/applications/editors/vim/plugins/utils/update.py. Do not edit!
{
  lib,
  buildVimPlugin,
  buildNeovimPlugin,
  fetchFromGitHub,
}:
final: prev: {
  copilot-vim = buildVimPlugin {
    pname = "copilot.vim";
    version = "2025-07-28";
    src = fetchFromGitHub {
      owner = "github";
      repo = "copilot.vim";
      rev = "51f80c0ed4f70d1c7e8c0ff11a792a9d84502c03";
      sha256 = "18zyw39flqgdpmnniii7yri169l2vlnsgckg5gr5la85r99pzfvk";
    };
    meta.homepage = "https://github.com/github/copilot.vim/";
    meta.hydraPlatforms = [ ];
  };
}
