#!/usr/bin/env nix
#!nix shell nixpkgs#bash nixpkgs#curl nixpkgs#jq nixpkgs#nix --command bash
# shellcheck shell=bash
#
# Update extra vim plugins from extra-plugins.csv
#
# The nixpkgs vim-plugins-updater doesn't work well outside nixpkgs since it
# tries to merge with all existing nixpkgs vim plugins. This script is a
# simpler alternative that just updates our small set of extra plugins.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
CSV_FILE="$SCRIPT_DIR/extra-plugins.csv"
OUT_FILE="$SCRIPT_DIR/extra-plugins.generated.nix"

# Fetch latest commit info from GitHub
fetch_github_latest() {
    local owner=$1
    local repo=$2
    local branch=${3:-HEAD}

    local api_url="https://api.github.com/repos/${owner}/${repo}/commits/${branch}"
    local response
    response=$(curl -sL "$api_url")

    local rev date
    rev=$(echo "$response" | jq -r '.sha')
    # Format: 2025-01-15
    date=$(echo "$response" | jq -r '.commit.committer.date' | cut -d'T' -f1)

    echo "$rev $date"
}

# Prefetch and get hash
prefetch_github() {
    local owner=$1
    local repo=$2
    local rev=$3

    # Try without submodules first (faster)
    local url="https://github.com/${owner}/${repo}/archive/${rev}.tar.gz"
    nix-prefetch-url --unpack "$url" 2>/dev/null
}

# Generate nix expression for a plugin
generate_plugin_nix() {
    local name=$1
    local owner=$2
    local repo=$3
    local rev=$4
    local date=$5
    local sha256=$6

    cat <<EOF
  ${name} = buildVimPlugin {
    pname = "${repo}";
    version = "${date}";
    src = fetchFromGitHub {
      owner = "${owner}";
      repo = "${repo}";
      rev = "${rev}";
      sha256 = "${sha256}";
    };
    meta.homepage = "https://github.com/${owner}/${repo}/";
    meta.hydraPlatforms = [ ];
  };

EOF
}

# Parse GitHub URL to owner/repo
parse_github_url() {
    local url=$1
    # Remove trailing slash and .git
    url="${url%/}"
    url="${url%.git}"
    # Extract owner/repo from https://github.com/owner/repo
    echo "${url#https://github.com/}"
}

# Main
echo "Updating extra vim plugins..."

# Start output file
cat > "$OUT_FILE" <<'EOF'
# GENERATED by ./pkgs/nvim/update.sh. Do not edit!
{
  lib,
  buildVimPlugin,
  buildNeovimPlugin,
  fetchFromGitHub,
}:
final: prev: {
EOF

# Skip header line and process each plugin
tail -n +2 "$CSV_FILE" | while IFS=, read -r repo_url branch alias; do
    # Skip empty lines
    [[ -z "$repo_url" ]] && continue

    owner_repo=$(parse_github_url "$repo_url")
    owner="${owner_repo%%/*}"
    repo="${owner_repo#*/}"

    # Use alias if provided, otherwise derive from repo name
    name="${alias:-$repo}"
    # Normalize name (replace . with -)
    name="${name//./-}"

    echo "Updating $name ($owner/$repo)..."

    # Fetch latest commit
    read -r rev date <<< "$(fetch_github_latest "$owner" "$repo" "$branch")"
    echo "  rev: $rev"
    echo "  date: $date"

    # Prefetch
    sha256=$(prefetch_github "$owner" "$repo" "$rev")
    echo "  sha256: $sha256"

    # Generate nix
    generate_plugin_nix "$name" "$owner" "$repo" "$rev" "$date" "$sha256" >> "$OUT_FILE"
done

# Close the attribute set
echo "}" >> "$OUT_FILE"

echo "Updated $OUT_FILE"

# Format the generated file
echo "Formatting..."
nix shell -f "$DOTFILES_DIR" phlipPkgs.nixfmt \
    --command nixfmt --width 80 "$OUT_FILE"

echo "Done!"
