# GENERATED by ./pkgs/applications/editors/vim/plugins/update.py. Do not edit!
{
  lib,
  buildVimPlugin,
  buildNeovimPlugin,
  fetchFromGitHub,
  fetchgit,
}: final: prev: {
  copilot-vim = buildVimPlugin {
    pname = "copilot.vim";
    version = "2025-03-24";
    src = fetchFromGitHub {
      owner = "github";
      repo = "copilot.vim";
      rev = "a9228e015528c9307890c48083c925eb98a64a79";
      sha256 = "0957a7y513n34b2bqysnlpnx3z6rphx8mmrsx3r5219hp19h2pyn";
    };
    meta.homepage = "https://github.com/github/copilot.vim/";
  };
}
